Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Linq;

namespace la_mia_pizzeria_static.Models
{
    [Table("Pizzas")]
    public class Pizza
    {
        [Key]
        public long Id { get; set; }

        [Required(ErrorMessage = "Campo obbligatorio")]
        [StringLength(30, ErrorMessage = "Massimo 30 caratteri")]

        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo obbligatorio")]
        [StringLength(100, ErrorMessage = "Massimo 100 caratteri")]
        [MinLength(5)]
        public string Descrizione { get; set; }

        [Required(ErrorMessage = "Campo obbligatorio")]
        public string FotoPath { get; set; }

        [Required(ErrorMessage = "Campo obbligatorio")]
        [Range(0.01, 999.99, ErrorMessage = "Il prezzo deve essere compreso tra 0,01 e 999,99.")]
        public float Prezzo { get; set; }

        //Relazione categoria
        public int? CategoriaId { get; set; }
        public Categoria? Categoria { get; set; }

        //Relazione ingredienti
        public List<Ingredienti>? Ingredienti { get; set; }

        public Pizza() { }

        // COSTRUTTORE
        public Pizza(string nome, string descrizione, string fotopath, float prezzo)
        {
            Nome = nome;
            Descrizione = descrizione;
            FotoPath = fotopath;
            Prezzo = prezzo;
        }

        public string GetCategoria()
        {
            if (Categoria == null)
            { 
            return "Nessuna categoria";
            } 
            return Categoria.Titolo;
        }
    }


}

Controllers/PizzaController.cs
using la_mia_pizzeria_static.Data;
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        [Authorize(Roles = "ADMIN,USER")]
        public IActionResult Index()
        {
                //List<Pizza> pizze = AggiungiPizze();

                //foreach (var pizza in pizze)
                //{
                //db.Pizze.Add(pizza);
                //}

                //db.SaveChanges();

                List<Pizza> pizze = PizzaManager.GetAllPizzas();
                return View("Index", pizze);
        }

        [Authorize(Roles = "ADMIN,USER")]
        public IActionResult Show(int id)
        {

            try
            {
                var pizza = PizzaManager.GetPizza(id);
                if (pizza != null)
                    return View(pizza);
                else
                    return NotFound();
                    //return View("Errore", new ErroreViewModel($"La pizza {id} non è stata trovata!"));
            }
            catch (Exception e)
            {
                //return View("Errore", new ErroreViewModel(e.Message));
                return BadRequest(e.Message);
            }

        }

        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            PizzaFormModel model = new PizzaFormModel();   
            model.Pizza = new Pizza();
            model.Categorie = PizzaManager.GetAllCategorie();
            model.CreaIngredienti();
           
            return View(model);        
        }

        //Action che fornisce la view con la form per creare una pizza
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create(PizzaFormModel data)
        {
            if (!ModelState.IsValid) 
            {
                List<Categoria> categorie = PizzaManager.GetAllCategorie();
                data.Categorie = categorie;
                data.CreaIngredienti();
                return View("Create", data);
            }
            PizzaManager.AggiungiPizza(data.Pizza, data.IngredientiSelezionati);
            return RedirectToAction("Index");

        }

        

        //Action che fornisce la view con la form per modificare una pizza
        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Update(int id)
        {
            var pizzaDaModificare = PizzaManager.GetPizza(id);

            if (pizzaDaModificare == null)
            {
                return NotFound();
            }
            else 
            {
                PizzaFormModel model = new PizzaFormModel();
                model.Pizza = pizzaDaModificare;
                model.Categorie = PizzaManager.GetAllCategorie();
                model.CreaIngredienti();


                return View(model);
            
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Update(int id, PizzaFormModel data)
        {
            if (!ModelState.IsValid)
            {
                data.Categorie = PizzaManager.GetAllCategorie();
                data.CreaIngredienti();
                return View("Update", data);
            }


            if(PizzaManager.ModificaPizza(id, data.Pizza.Nome, data.Pizza.Descrizione, data.Pizza.FotoPath, data.Pizza.Prezzo, data.Pizza.CategoriaId, data.IngredientiSelezionati))
            {
                return RedirectToAction("Index");
            }
            else 
            {
                return NotFound();
            }

        }

        //Action per eliminare una pizza
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Delete(int id)
        {
            if (PizzaManager.EliminaPizza(id))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return NotFound();
            }

        }

        //private List<Pizza> AggiungiPizze()
        //{
        //List<Pizza> listaPizze = new List<Pizza>
        //{
        //new Pizza { Nome = "Margherita", Descrizione = "Pomodoro, Mozzarella, Basilico", FotoPath = "https://images.prismic.io/eataly-us/ed3fcec7-7994-426d-a5e4-a24be5a95afd_pizza-recipe-main.jpg?auto=compress,format", Prezzo = 5.99f },
        //new Pizza { Nome = "Boscaiola", Descrizione = "Mozzarella, Salsiccia, Funghi", FotoPath = "https://www.alfaforni.com/wp-content/uploads/2018/08/pizza-boscaiola-wild-traditional-mushroom-pizza.jpg", Prezzo = 8.99f },
        //new Pizza { Nome = "Parmigiana", Descrizione = "Pomodoro, Mozzarella, Melanzane, Parmigiano, Basilico", FotoPath = "https://wips.plug.it/cips/buonissimo.org/cms/2023/01/pizza-con-parmigiana-di-melanzane.jpg", Prezzo = 7.99f },
        //new Pizza { Nome = "Capricciosa", Descrizione = "Pomodoro, Mozzarella, Funghi, Prosciutto Crudo, Uovo, Olive", FotoPath = "https://www.italianmenumaster.com/images/67.jpg", Prezzo = 8.99f },

        //};

        //return listaPizze;
        //}
    }
}

Views/Pizza/Create.cshtml
@using la_mia_pizzeria_static.Data;
@model PizzaFormModel

@{
    Layout = "_PizzeriaLayout";
    ViewData["Title"] = "Crea nuova pizza";
}

@if (User.IsInRole("ADMIN"))
{
<div>
    <div class="wrapper">
        <div class="form-container">
            <form asp-controller="Pizza" asp-action="Create" method="post">
                @Html.AntiForgeryToken()

                <div>
                    <label for="inputNome">Inserisci il nome:</label>
                    <br />
                    <input asp-for="Pizza.Nome" class="create-input" id="inputNome"/>
                    <br />
                    <span asp-validation-for="Pizza.Nome" class="text-danger"></span>
                </div>
                <div>
                    <label for="InputDescrizione">Inserisci gli ingredienti:</label>
                    <br />
                    <input asp-for="Pizza.Descrizione" class="create-input" id="inputDescrizione"/>
                    <br />
                    <span asp-validation-for="Pizza.Descrizione" class="text-danger"></span>
                </div>
                <div>
                    <label for="inputFotoPath">Inserisci la foto:</label>
                    <br />
                    <input asp-for="Pizza.FotoPath" class="create-input" id="inputFotoPath"/>
                    <br />
                    <span asp-validation-for="Pizza.FotoPath" class="text-danger"></span>
                </div>
                <div>
                    <label for="inputPrezzo">Inserisci un prezzo:</label>
                    <br />
                    <input asp-for="Pizza.Prezzo" class="create-input" id="inputPrezzo" />
                    <br />
                    <span asp-validation-for="Pizza.Prezzo" class="text-danger"></span>
                </div>
                <strong>Categoria:</strong>
                <select asp-for="Pizza.CategoriaId" rows="10" class="d-block w-100">
                    <option value=""></option>
                    @foreach (Categoria categoria in Model.Categorie)
                    {
                        @if (Model.Pizza.CategoriaId == categoria.Id)
                        {
                            <option value="@categoria.Id" selected>@categoria.Titolo</option>
                        }
                        else
                        {
                            <option value="@categoria.Id">@categoria.Titolo</option>
                        }
                    }
                </select>
                <div>
                    <strong>Ingredienti: </strong>
                    @for (int i = 0; i < Model.Ingredienti.Count; i++)
                    {
                        <div>
                            <input type="checkbox" name="SelectedTags" value="@Model.Ingredienti[i].Value"
                            @(Model.IngredientiSelezionati.Contains(Model.Ingredienti[i].Value) ? "checked" : "") />
                            @Model.Ingredienti[i].Text
                        </div>
                    }
                </div>
                <div>
                    <input type="submit" class="submit-button" value="Salva">
                </div>
            </form>
        </div>
    </div>
    </div>
}
else
{
    <p>WRONG NEIGHBORHOOD DAWG</p>    
}

Views/Pizza/Index.cshtml
@model List<Pizza>;
@{
    ViewData["Title"] = "Home Page";
    Layout = "_PizzeriaLayout";
}


    <div class="wrapper">
            <h1 class="center m-5">La nostra pizzeria!</h1>
                <div class="card-container" style="">
                    @foreach (var pizza in Model)
                    {
                        <div class="card mx-5" style="width: 300px; height: 350px;">
                            <a href="#">
                                <div class="card-top" style="border-bottom: 1px solid gray;">
                                    <a href="@Url.Action("Show", "Pizza", new{ id = pizza.Id})">
                                    <img src="@pizza.FotoPath" alt="Foto Pizza" style="max-width: 200px; height: 150px;" />    
                                    </a>
                                </div>
                            </a>
                            <div class="card-bot">
                                <h3 class="card-title">@pizza.Nome</h3>
                                <h5 class="d-inline" style="font-weight: 500">Ingredienti: </h5>
                                <p class="card-text" style="font-style:italic;">@pizza.Descrizione</p>
                                <br />
                                <h5 class="d-inline" style="font-weight: 500">Prezzo: </h5>
                                <span class="card-text">@pizza.Prezzo €</span>
                            </div>
                            <a href="@Url.Action("Update", "Pizza", new{ id = pizza.Id})">
                                Modifica
                            </a>
                        </div>
                        <form asp-controller="Pizza" asp-action="Delete" asp-route-id="@pizza.Id" method="post">
                            @Html.AntiForgeryToken()
                            <input type="submit" value="Elimina" />
                        </form>
                    }

                    <a href="@Url.Action("Create", "Pizza")">
                        Aggiungi una nuova pizza
                    </a>
                </div>
    </div>
   

Views/Pizza/Show.cshtml
@using la_mia_pizzeria_static.Data;
@model Pizza

@{
    Layout = "_PizzeriaLayout";
}

<h1>Ecco la @Model.Nome </h1>
<img src="@Model.FotoPath" alt="@Model.Nome" />
<p>@Model.Descrizione</p>
<strong>Prezzo: </strong>
<span>@Model.Prezzo </span>
<span> Categoria: @Model.GetCategoria() </span>
<div>
    <strong>Ingredienti: </strong>
    
    @if (Model.Ingredienti?.Count > 0) 
        @foreach (var ingrediente in Model.Ingredienti)
        {
            <div style="background-color: #AAAAAA; display: flex; justify-content: center; align-items: center;
                        border-radius: 3px; border-style: solid; border-color: #AAAAAA; padding: 2px;">
                    @ingrediente.Nome
            </div>
        }
        else
        {
            <p>Non ci sono ingredienti selezionati</p>
        }
</div>

<div class="row">
    <div class="col"><a href="@Url.Action("Index", "Pizza")">BACK</a></div>
</div>

Views/Pizza/Update.cshtml
@using la_mia_pizzeria_static.Data;
@model PizzaFormModel

@{
    Layout = "_PizzeriaLayout";
    ViewData["Title"] = "Crea nuova pizza";
}


@if (User.IsInRole("ADMIN"))
{
<div>
    <div class="wrapper">
        <div class="form-container">
            <form asp-controller="Pizza" asp-action="Update" asp-route-id="@Model.Pizza.Id" method="post">
                @Html.AntiForgeryToken()

                <div>
                    <label for="inputNome">Inserisci il nome:</label>
                    <br />
                    <input asp-for="Pizza.Nome" class="create-input" id="inputNome"/>
                    <br />
                    <span asp-validation-for="Pizza.Nome" class="text-danger"></span>
                </div>
                <div>
                    <label for="InputDescrizione">Inserisci gli ingredienti:</label>
                    <br />
                    <input asp-for="Pizza.Descrizione" class="create-input" id="inputDescrizione" />
                    <br />
                    <span asp-validation-for="Pizza.Descrizione" class="text-danger"></span>
                </div>
                <div>
                    <label for="inputFotoPath">Inserisci la foto:</label>
                    <br />
                    <input asp-for="Pizza.FotoPath" class="create-input" id="inputFotoPath" />
                    <br />
                    <span asp-validation-for="Pizza.FotoPath" class="text-danger"></span>
                </div>
                <div>
                    <label for="inputPrezzo">Inserisci un prezzo:</label>
                    <br />
                    <input asp-for="Pizza.Prezzo" class="create-input" id="inputPrezzo" />
                    <br />
                    <span asp-validation-for="Pizza.Prezzo" class="text-danger"></span>
                </div>
                <div>
                    <strong>Categoria:</strong>
                    <select asp-for="Pizza.CategoriaId" rows="10" class="d-block w-100">
                        <option value=""></option>
                        @foreach (Categoria categoria in Model.Categorie)
                        {
                            @if (Model.Pizza.CategoriaId == categoria.Id)
                            {
                                <option value="@categoria.Id" selected>@categoria.Titolo</option>
                            }
                            else
                            {
                                <option value="@categoria.Id">@categoria.Titolo</option>
                            }
                        }
                    </select>
                </div>
                <div>
                    <strong>Ingredienti: </strong>
                    @for (int i = 0; i < Model.Ingredienti.Count; i++)
                    {
                        <div>
                            <input type="checkbox" name="IngredientiSelezionati" value="@Model.Ingredienti[i].Value"
                            @(Model.IngredientiSelezionati.Contains(Model.Ingredienti[i].Value) ? "checked" : "") />
                            @Model.Ingredienti[i].Text
                        </div>
                    }
                </div>
                <div>
                    <input type="submit" class="submit-button" value="Salva">
                </div>
            </form>
        </div>
    </div>
</div>
}
else
{
<p>WRONG NEIGHBORHOOD DAWG</p>
}